name: RenovaAttribute
main: org.renova.renovaattribute.RenovaAttribute
version: '${version}'
depend:
  - AyCore
softdepend:
  - MythicMobs
author: AiYo
api-version: '1.21'
commands:
  renovaattribute:
    aliases:
      - ra
